app/resources/api/v3/public/card_resource.rb
app/resources/api/v3/public/printing_resource.rb

Fix API after importer/schema changes.

---

app/resources/api/v3/public/printing_resource.rb
config/application.rb

Add images attribute for printings, with nrdb-classic images.

---

lib/tasks/cards.rake

This won't work until the v2 changes are in the JSON repo.

Update json paths and utilize new schema.

---

db/schema.rb

db:reset will generate this and checking it in means we can avoid some diffs later.
Looks like this is basically a sorted version of what you submitted.

Check in rails-generated version of db/schema.rb

---

app/models/printing.rb
app/resources/api/v3/public/printing_resource.rb
lib/card_search_parser.rb
lib/card_search_query_builder.rb
lib/printing_search_parser.rb
lib/printing_search_query_builder.rb
test/unit/printing_search_parser_test.rb
test/unit/printing_search_query_builder_test.rb

initial version.
too much duplication with cards.
Needed some model updates to wire everything up properly.

Printing search

---

db/migrate/20220923032558_update_unified_restrictions_to_version_3.rb
db/schema.rb
db/views/unified_restrictions_v03.sql
lib/card_search_parser.rb
lib/card_search_query_builder.rb
lib/printing_search_parser.rb
lib/printing_search_query_builder.rb

in_restriction means "there is an entry on a restriction for this card."  This will let us do queries like:
http://localhost:3000/api/v3/public/cards?filter[search]=in_restriction:true%20restriction_id:standard_ban_list_22_09
or
http://localhost:3000/api/v3/public/cards?filter[search]=in_restriction:true
to retrieve only cards on a specific or any restriction.

Add in_restriction field to unified_restrictions.

---

app/models/card.rb

Fill in the restriction relationships for cards.

---

app/resources/api/v3/public/format_resource.rb
app/resources/api/v3/public/restriction_resource.rb
db/migrate/20220925113944_update_unified_restrictions_to_version_4.rb
db/migrate/20220925225117_remove_value_from_restrictions_cards_global_penalty.rb
db/schema.rb
db/views/unified_restrictions_v04.sql
lib/card_search_parser.rb
lib/card_search_query_builder.rb
lib/printing_search_parser.rb
lib/printing_search_query_builder.rb
lib/tasks/cards.rake
test/unit/card_search_query_builder_test.rb
test/unit/printing_search_query_builder_test.rb

Global penalties never reduced you influence limit by anything other than 1, so I'm reducing the complexity of dealing with them.

Flattened global penalty field to array instead of a mapping

---

config/environments/development.rb
config/initializers/cors.rb
docker-compose.override.yml
docker-compose.yml

we'll need to tidy this up later, but i want to make deployments a checkout, build, go operation.
These are the changes we have on the api-preview.netrunnerdb.com server.  Bringing them into the repo for now as a temporary measure.

Sync up API preview server changes.

---

README.md
config/environments/development.rb
docker-compose.override.yml
docker-compose.yml

This is in preparation for hooking up to an identity provider and an API frontend, which will be configured in a separate project.

Update docker config to use a new null_signal network.

---

lib/deck_validator.rb
test/fixtures/cards.yml
test/fixtures/factions.yml
test/unit/deck_validator_test.rb

Add deck validation for cards with alternate limits.

Deckbuilding id restrictions

---

app/resources/api/v3/public/card_resource.rb
app/resources/api/v3/public/printing_resource.rb
db/migrate/20231015222243_add_designed_by_to_cards.rb
db/migrate/20231015222301_add_released_by_to_cycles_and_sets.rb
db/migrate/20231016210204_add_released_by_to_printings.rb
db/migrate/20231017100710_update_unified_printings_to_version_5.rb
db/migrate/20231017101245_update_unified_cards_to_version_4.rb
db/schema.rb
db/views/unified_cards_v04.sql
db/views/unified_printings_v05.sql
lib/tasks/cards.rake

Add `designed_by` field to cards.
Add `released_by` field to card cycles, card sets, cards, and printings.

Start of Designed and Released by Support in the API.

---

app/controllers/api/v3/private/user_controller.rb
app/resources/api/v3/private/user_resource.rb
config/routes.rb

this is overdue, but required now that we have auth integrated into v2.

Return a normal JSONAPI response for user endpoint.

---

app/controllers/api/v3/public/decklists_controller.rb
app/models/decklist.rb
app/models/decklist_card.rb
app/resources/api/v3/public/decklist_resource.rb
config/routes.rb
db/migrate/20240406181616_create_decklists_and_decklist_slots.rb
db/schema.rb

Add decklist tables, resource and controller.

---

lib/tasks/import_decklists.rake

This can be invoked with `bundle exec rake 'import_decklists:import[2024-03-29]'`

Basic public decklist importer from V2.

---

app/resources/api/v3/public/card_resource.rb
app/resources/api/v3/public/printing_resource.rb
db/migrate/20240512213120_add_pronunciation_to_cards.rb
db/migrate/20240512220127_update_unified_cards_to_version_6.rb
db/migrate/20240512220325_update_unified_printings_to_version_8.rb
db/schema.rb
db/views/unified_cards_v06.sql
db/views/unified_printings_v08.sql
lib/tasks/cards.rake

currently only the Liberation Cycle is supported. Waiting to hear back more from Narrative before going for Borealis

Pronunciation Guide integration

---

app/models/decklist.rb
app/resources/api/v3/public/decklist_resource.rb

This allows queries to include the card data for the ID and cards in the deck.
example request: 
http://localhost:3000/api/v3/public/decklists/c382a134-4a93-444a-aeec-ed18985876a9?include=identity_card,cards

Add identity_card and cards relations to decklist.

---

app/models/deck.rb
app/models/decklist.rb
app/models/faction.rb
app/models/unified_card.rb
app/resources/card_resource.rb
app/resources/deck_resource.rb
app/resources/decklist_resource.rb

Fix card relationships and filters for deck (private) and decklist (public) resources.

Deck and decklist relationships

---

app/models/card_type.rb
spec/resources/card_subtype/reads_spec.rb
spec/resources/card_type/reads_spec.rb
test/fixtures/card_subtypes.yml
test/fixtures/printings_card_subtypes.yml

Update fixtures and relationships accordingly.

Add spec files for Card Type & Subtype resources.

---

app/models/card.rb
app/models/concerns/card_abilities.rb
app/models/printing.rb
app/resources/card_resource.rb
app/resources/printing_resource.rb
spec/resources/card/reads_spec.rb
spec/resources/printing/reads_spec.rb
test/fixtures/raw_cards.yml
test/fixtures/raw_printings.yml

last 2 public resources have spec tests now!
This also moves some attribute calculation from the resource to the model.

Add specs for card and printing resources.

---

docker-compose.yml

This lets us deploy to specific versions with just .env file changes.

Add version tags to docker compose file.

---

lib/tasks/cards.rake

Fix snapshot active field to default false on import.

---

app/models/decklist.rb
lib/tasks/import_decklists.rake

This fixes an issue where the importer was unable to import the same date twice.

Delete decklist_cards instead of nullifying. Add transaction to import.

---

app/resources/card_resource.rb
db/migrate/20241231061440_update_unified_cards_to_version_9.rb
db/schema.rb
db/views/unified_cards_v09.sql

This also adds layout_id to unified_cards

Expose layout_id on card resource.

---

app/models/printing_face.rb
db/migrate/20250105032459_create_printing_faces.rb
db/migrate/20250105041622_update_unified_printings_to_version_10.rb
db/schema.rb
db/views/unified_printings_v10.sql
lib/tasks/cards.rake

Import printing faces and update unified_printings.

---

config/initializers/apitome.rb

This should resolve the performance issue on the API docs.

Switch API docs to multi-page format.
