app/models/card_cycle.rb
app/models/card_set.rb
app/models/faction.rb
app/models/printing.rb
app/models/side.rb
app/resources/api/v3/public/card_cycle_resource.rb
app/resources/api/v3/public/card_resource.rb
app/resources/api/v3/public/card_set_resource.rb
app/resources/api/v3/public/faction_resource.rb
app/resources/api/v3/public/printing_resource.rb
app/resources/api/v3/public/side_resource.rb

fill in the missing gaps for relationships in the models and resources.

Moar relationships

---

app/resources/api/v3/public/card_cycle_resource.rb
app/resources/api/v3/public/card_resource.rb
app/resources/api/v3/public/card_set_resource.rb
app/resources/api/v3/public/card_set_type_resource.rb
app/resources/api/v3/public/card_subtype_resource.rb
app/resources/api/v3/public/card_type_resource.rb
app/resources/api/v3/public/faction_resource.rb
app/resources/api/v3/public/printing_resource.rb
app/resources/api/v3/public/side_resource.rb

This only produces GET routes for these resources, which is what we want for the public API.

Make all public API resources immutable.

---

lib/tasks/cards.rake

When i added the cycle release date function, i tested on a pre-populated database, but if there are no sets imported, the task crashes on first run.  Oops!

Fix ordering for card import first run.

---

Gemfile
Gemfile.lock
config/initializers/cors.rb

This PR:
* adds back in the `rack-cors` gem
* allows CORS `get`/`option`/`head` requests from any origin

add rack-cors and update CORS headers

---

app/controllers/api/v3/public/illustrators_controller.rb
app/models/illustrator.rb
app/models/illustrator_printing.rb
app/models/printing.rb
app/resources/api/v3/public/illustrator_resource.rb
app/resources/api/v3/public/printing_resource.rb
config/routes.rb
db/migrate/20220625035145_create_illustrator_tables.rb
db/migrate/20220625170812_rename_printing_illustrator.rb
db/schema.rb
lib/tasks/cards.rake

Fixes #35 
I need to wait until the JSON repo has been tidied up before submitting this.

Add illustrator model, resource, and API. Update importer to support it.

---

app/resources/api/v3/public/snapshot_resource.rb

Snapshots now directly expose their card sets/cycles instead of linking to a card pool

---

app/resources/api/v3/public/card_pool_resource.rb
app/resources/api/v3/public/format_resource.rb
app/resources/api/v3/public/snapshot_resource.rb

Snapshots:
- exposed `card_pool_id`
- exposed `restriction_id`
Formats:
- exposed `snapshot_ids`
Card pools:
- exposed `card_cycle_ids`
- exposed `card_set_ids`
- exposed `card_ids`
Without this change you have to make an additional api call to find these values; I don't know if that's how we want it but it's a non-insignificant hassle for updating the Discord bot.

Expose some additional fields for ease of use

---

app/resources/api/v3/public/card_cycle_resource.rb
app/resources/api/v3/public/card_set_resource.rb
db/migrate/20220831025326_add_legacy_code_to_card_cycles.rb
db/migrate/20220831025337_add_legacy_code_to_card_sets.rb
db/schema.rb
lib/tasks/cards.rake

Add support for legacy_codes to enable interop with NRDB classic.
Since the new app has different ids (the mechanical transformation of the names or card titles), we need to be explicit about the mapping.

Add legacy_code support for cycles and sets.

---

lib/tasks/cards.rake

It turns out the database was already set up for this and the field was already exposed in the resource.

Updated importer to add card set types' descriptions

---

app/resources/api/v3/public/format_resource.rb
app/resources/api/v3/public/restriction_resource.rb

- packaged each restriction's banlist, restricted list, etc. in a single field `verdicts`
- added an attribute to restrictions counting the number of cards affected by them
- exposed the id of the active restriction of each format

Some qol changes in restrictions

---

app/resources/api/v3/public/card_resource.rb

This lets you get a link for a card (not printing) without running a separate api call on printings. I don't know if this would be better as a relationship.

Exposed the latest printing id of each card

---

app/resources/api/v3/public/card_resource.rb
app/resources/api/v3/public/format_resource.rb

- Fixed cards assuming their printings were in release date order
- Exposed active card pool ID in formats

Two small things

---

app/models/card.rb
app/resources/api/v3/public/card_resource.rb
app/resources/api/v3/public/printing_resource.rb
lib/card_search_parser.rb
lib/card_search_query_builder.rb
lib/printing_search_parser.rb
lib/printing_search_query_builder.rb
lib/tasks/cards.rake

This wires up attributes from #99 to the resources in the API and the search filters.
Cards and printings now have this:
```
"card_abilities": {
"additional_cost": false,
"advanceable": false,
"gains_subroutines": false,
"interrupt": false,
"link_provided": null,
"mu_provided": null,
"num_printed_subroutines": null,
"on_encounter_effect": false,
"performs_trace": false,
"recurring_credits_provided": "X",
"trash_ability": false
},
```
and each attribute is wired up in the filter[search] syntax.
This also adds handling of X for numeric types and updates X agenda points to be -1 instead of NULL to make our X types more consistent (straight costs still need it).

Add first batch of advanced card attributes to API & search.

---

app/resources/api/v3/public/card_resource.rb
app/resources/api/v3/public/printing_resource.rb

This fixes a weird issue with the search operator.
Before this, a query like: http://localhost:3000/api/v3/public/cards?filter%5Bsearch%5D=in_restriction%3Atrue&page[limit]=250&page[offset]=0
would return paging links along the default 100 items lines, but the data would only have a handful of records.  It was pulling back the same card_id from the unified_restrictions join multiple times (1 per restriction a card is on), applying paging, then deduping before the results were sent.
This makes things behave as expected.
Note: The rails query thing does "find all the ids" then "select * from the model's table where id = ?" for each one.  :/. The query above takes almost 400ms on my local machine, but I think with a materialized view we can get that down < 100ms pretty easily.

Make the search operator query distinct.

---

app/resources/api/v3/public/format_resource.rb

The [current version](https://api-preview.netrunnerdb.com/api/v3/public/formats/standard/) has the most recent two IDs placed out of order. Debugging suggests the server is cursed.
Let me know if this isn't the best way to do this.

Forced the snapshot and restriction IDs of formats to be ordered

---

app/views/apitome/docs/_example.html.erb
app/views/apitome/docs/_explanation.html.erb

The doc tests can have an explanation that accepts markdown.  The default partials for apitome did not match what rspec_api_documentation generated, so these were needed to fix that functionality.

Add partials that fix explanation rendering.

---

app/resources/api/v3/public/printing_resource.rb
doc/api/index.json
doc/api/printings/filter_-_distinct_cards.json

This removes reprints from the results of `printings`, leaving only the most recent version. This doesn't currently account for legality (the Spark problem).

Added `distinct_cards` filter to remove reprints

---

app/controllers/concerns/jwt_authorization_concern.rb

Return a proper JSON::API error structure instead of an empty JSON object if the request is unauthorized.

Return a proper error when unauthorized.

---

app/models/printing.rb
app/models/snapshot.rb
app/models/unified_printing.rb
app/resources/api/v3/public/printing_resource.rb
app/resources/api/v3/public/snapshot_resource.rb

- Printings/unified printings can see their type (through their card)
- Snapshots can see their cycles and sets (through their card pools)

Added some missing relationships

---

app/controllers/api/v3/public/validate_deck_controller.rb
config/routes.rb

Expose an API endpoint for deck validation using the new deck validation library.
This echoes the input format of the deck controller, but is a bit weird because this isn't a normal JSONAPI operation.
If the request is valid, the response will return the original request with 2 extra attributes added: `is_valid` and `validation_errors`, like this:
```
{
"data": {
"attributes": {
"is_valid": false,
"validation_errors": [
"Card `hostile_architecture` has a deck limit of 3, but 4 copies are included.",
"Deck with size 50 requires [22,23] agenda points, but deck only has 20"
]
}
}
```
A valid deck will look like this:
```
{
"data": {
"attributes": {
"is_valid": true,
"validation_errors": []
}
}
```

Add an API endpoint for deck validation.

---

lib/tasks/krakend.rake

By default this will generate for our docker API server hostname and our Keycloak docker hostname.
This config includes our API Docs endpoint and programmatically generates endpoints for all of the API routes.

Add a rake task to generate Krakend config for our API.

---

app/resources/api/v3/public/restriction_resource.rb

PR for my suggestion here: #199 
Changes restriction `points` and `universal_faction_cost` from:
```json
{
"universal_faction_cost": {
"1": [
"architect",
...
],
"3": [
"blackmail",
...
]
},
"points": {
"1": [
"24_7_news_cycle",
...
],
"2": [
"accelerated_diagnostics",
...
],
"3": [
"account_siphon",
...
]
}
}
```
to:
```json
{
"universal_faction_cost": {
"architect": 1,
"blackmail": 3,
...
},
"points": {
"24_7_news_cycle": 1,
"accelerated_diagnostics": 2,
"account_siphon": 3,
...
}
}
```
This has a few benefits:
* The value is now returned as a number instead of a string which the client would need to parse.
* It's easier for the client to lookup the value for a card
`const points = restriction.verdicts.points[card_id]`.

Make restiction points and universal_faction_cost a hash of card_id and value

---

lib/tasks/cards.rake

Use sets instead of arrays when importing data

---

.devcontainer/devcontainer.json
app/models/card.rb
app/models/card_pool.rb
app/models/card_pool_card.rb
app/resources/card_pool_resource.rb
app/resources/card_resource.rb
app/resources/printing_resource.rb
spec/resources/card/reads_spec.rb
spec/resources/card_pool/reads_spec.rb
spec/resources/printing/reads_spec.rb

Add {card,printing} <-> card_pool relationships

---

.github/workflows/ci.yml
spec/spec_helper.rb

`rails t` and `rspec` are generating independent coverage reports.  Combine them to improve coverage accuracy.

Combine coverage reports from unit and rspec tests.

---

app/models/card.rb
app/resources/card_resource.rb
app/resources/printing_resource.rb

This reduces /cards and /printings default load times by ~80+% by not falling back to relations for fields that already exist in the unified_{cards,printings} tables.

Use DB attributes to avoid unneccessary queries from relations.

---

.devcontainer/devcontainer.json
.github/workflows/ci.yml
Dockerfile
Gemfile
Gemfile.lock

Update to the latest ruby release in both the devcontainer and the main Dockerfile.

Update to Ruby 3.3.6.

---

lib/search_query_builder.rb
test/unit/card_search_query_builder_test.rb
test/unit/printing_search_query_builder_test.rb

Lightly strip input text to allow matches from unicode input.

---

app/controllers/illustrators_controller.rb
app/resources/illustrator_resource.rb
app/resources/printing_resource.rb

Because printings may have multiple illustrators and an array field AND there is a join table, the default many_to_many implementation can't join these tables properly.
All of the loaded printings were attached to the first record before this fix and the query took 10x longer.

Fix relationship problem for illustrators <-> printings.

---

app/models/card_face.rb
app/models/card_face_card_subtype.rb
db/migrate/20241230053539_add_layout_id_to_cards.rb
db/migrate/20241230055434_create_card_faces.rb
db/migrate/20241230055711_create_card_faces_card_subtypes.rb
db/schema.rb
lib/tasks/cards.rake

I'm going to take a slightly different approach than #185 from @distributive , but there are some things I am lifting from that PR, so thanks!
I'll break this work into a couple of pieces, but the plan is to expose face data on cards and printings rather than have them be their own resources.

Add basic import and storage for card face info.

---

db/migrate/20250105055917_update_unified_printings_to_version_11.rb
db/schema.rb
db/views/unified_printings_v11.sql

Follow the yellow brick road, i mean #174

Fix face columns to be properly normalized in unified_printings.

---

app/models/printing.rb
app/resources/printing_resource.rb
spec/resources/printing/reads_spec.rb

#174 
These images don't exist out on our cloud storage yet, but boy oh boy they will soon!

Add images to printing faces. Refactor images method.

---

app/resources/application_resource.rb
config/initializers/graphiti.rb

This does basic response caching.
It doesn't appear to work for included resources, but will still be a bit helpful, so i'm pushing this.

Cache public resource rendering for a week.

---

lib/tasks/cards.rake

This now properly calculates cycle release date as the minimum date_release for the packs in the set.

Fix card cycles release date calculation

---

.devcontainer/Dockerfile

This tripped me up today because I get getting 3.1 in the devcontainer.

Update Dockerfile to Ruby 3.3

---

spec/spec_helper.rb

I accidentally changed this a couple of weeks back.  Sorry!

Set API doc format back to JSON.

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
README.md
docker-compose.override.init.yml
docker-compose.yml

Making this change to the suggested environment in the docs and in the devcontainer setup to avoid collisions with Cobra.

Use bin/setup in devcontainer and move to port 3100 for dev.

---

app/models/printing.rb
app/resources/card_resource.rb
app/resources/printing_resource.rb
spec/resources/card_resource_reads_spec.rb
spec/resources/printing_resource_reads_spec.rb

I really wanted to add some tests for this, but I'm not really sure how to go about that. It didn't look like it belonged in acceptance/cards_spec.rb or resources/card_resource_reads_spec.rb. Also, not really sure how to test a resource specifically.

Check that the card is NSG before serving xlarge images
